version: '3'

services:
  ledfx:
    image: serturx/ledfx-git:2.0.71-a # Fork includes fixes to run on a RaspberryPi3 B
    container_name: ledfx
    environment:
      - HOST=192.168.0.15
      - FORMAT=-r 44100 -f S16_LE -c 2
      - SQUEEZE=1
    ports:
      - 8888:8888 # Can be changed to <your-port>:8888
    volumes:
      - ./config/ledfx-config.json:/app/ledfx-config/config.json
      - ./config/ledfx-config.yaml:/app/ledfx-config/config.yaml
      - ./audio/ledfx.audio:/app/audio/stream # Created by prepare_airplay.sh
  shairport-sync:
    image: mikebrady/shairport-sync:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./audio/shairport.audio:/app/shairport.audio
      - ./config/shairport.conf:/etc/shairport-sync.conf
    devices:
      - "/dev/snd" # ALSA device
    logging:
      options:
        max-size: "200k"
        max-file: "10"
  bt-ctl:
    image: serturx/bt-ctl:latest
    volumes:
      - "/var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket"
    ports:
      - 8080:8080
